"""PC XModel -> PS3 XModel, node by node.

A PC model (``pc.PCXModelHandler``: XModel 0xfc, XSurface 0x44, GfxPackedVertex 32 bytes)
becomes the node the PS3 handler (``xfile/handlers/xmodel.py``: XModel 0xf8, XSurface
0x5c) writes. Rules, each checked on the 293 models PC and PS3 mp_nuked share
(``compare_xmodels``; docs/convert.md section 12):

- header: PC[0x0, 0x28) + four lodInfo of 28 bytes (PC 32: the trailing lod,
  smcIndexPlusOne, smcAllocBits and unused bytes are dropped) + lodDistAutoGenerated and 7
  bytes + PC[0xac, 0xe0) + 12 zero bytes + memUsage and flags + PC[0xec, 0xfc) (the PC
  ``bad`` word is dropped), every field swapped; memUsage per ``ps3_mem_usage``.
- surface flags: PC flags | 1 (quantised positions) | 4 when every vertex has the same
  colour (constant colour), which is then stored at XSurface +0x58 (0 otherwise).
  ``flags & 7`` picks the PS3 vertex format (docs/extract.md 3.2).
- packed positions: offset = (min + max) * 0.5 per axis in f32 (all 1732 quantised PS3
  surfaces); one exponent e for the three axes, the smallest e >= 0 with 2^e >= the
  largest half extent; s16 = round((p - offset) * 32768 / 2^e); binormal sign +1 ->
  32767, -1 -> -32768.
- normal, tangent: PC PackedUnitVec -> CMP 11:11:10 (``world.cmp_pack``); uv: the PC
  packed half pair is one u32, swapped; colour bytes B, G, R, A -> R, G, B, A.
- XSurface +0x54 is 0x4b on every quantised PS3 surface (meaning INFERRED: unknown).
- collSurfs: PS3 0x24 per surface, the PC collTris pointer and count dropped.
- everything else (bones, rigid vertex lists, collision trees, blend data, high mip
  bounds, collmaps, physPreset) has the PC layout and is swapped.

Bone names are script string indices: ``convert_xmodel`` takes a function mapping a PC
index to the target zone's. Materials are kept as the PC handler parsed them; a caller
splicing the model into a PS3 zone replaces each by the target's material (by name).
Data the PC zone shares by offset pointer is fetched through ``fetch`` and written
inline (the PS3 linker shares more, by content; sharing is an optimisation).
"""

from __future__ import annotations

import math
import struct
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

import numpy as np

from opent5.convert.swap import swap_struct
from opent5.convert.world import ConvertError, cmp_pack, pc_unit_vectors
from opent5.xfile.constants import PTR_INLINE

PC_XMODEL = 0xFC
PS3_XMODEL = 0xF8
PC_XSURFACE = 0x44
PS3_XSURFACE = 0x5C
#: XSurface +0x54 on every quantised PS3 surface of mp_nuked (1819 of 1820; the one
#: unquantised surface has 0).
QUANTISED_MARK = 0x4B

FLAG_QUANTISED = 1
FLAG_SKINNED = 2
FLAG_CONSTANT_COLOUR = 4

PC_PACKED_VERTEX = np.dtype(
    [
        ("xyz", "<f4", 3),
        ("binormal_sign", "<f4"),
        ("colour", "u1", 4),
        ("uv", "<u4"),
        ("normal", "u1", 4),
        ("tangent", "u1", 4),
    ]
)

#: Fetch(raw pointer value, byte count) -> the bytes a PC offset pointer names.
Fetch = Callable[[int, int], bytes]


@dataclass
class ModelResult:
    node: dict
    notes: list[str] = field(default_factory=list)


def _u32(data: bytes, off: int, fmt: str = "<I") -> int:
    return struct.unpack_from(fmt, data, off)[0]


def xmodel_header(pc_header: bytes) -> bytes:
    """PS3 XModel header (0xf8) from a PC one (0xfc, little-endian)."""
    if len(pc_header) != PC_XMODEL:
        raise ConvertError(f"PC XModel header: expected {PC_XMODEL} bytes, found {len(pc_header)}")
    sw = swap_struct("XModel", pc_header)
    out = bytearray(sw[0:0x28])
    for i in range(4):
        base = 0x28 + 32 * i
        out += sw[base : base + 28]
    # 0x98: lodDistAutoGenerated (PC +0xa8) and 7 bytes, zero in all 293 mp_nuked models.
    out += bytes([sw[0xA8]]) + bytes(7)
    out += sw[0xAC:0xE0]
    # PS3 0xd4..0xdf: 12 bytes, zero in all 293 mp_nuked models; memUsage and flags then
    # sit at 0xe0 and 0xe4 (PC 0xe0, 0xe4); the PC ``bad`` word (+0xe8) has no PS3 place.
    out += bytes(12) + sw[0xE0:0xE8]
    out += sw[0xEC:PC_XMODEL]
    if len(out) != PS3_XMODEL:
        raise AssertionError(len(out))
    return bytes(out)


def quantise(xyz: np.ndarray) -> tuple[np.ndarray, int, np.ndarray]:
    """(offset f32[3], exponent, s16 positions) for one surface's float positions."""
    xyz = xyz.astype(np.float32)
    lo, hi = xyz.min(axis=0), xyz.max(axis=0)
    offset = ((lo + hi) * np.float32(0.5)).astype(np.float32)
    half = float(((hi - lo) * np.float32(0.5)).max())
    # 2^4 = 16 for a half extent of 16.000002 (p_us_table_art02 surface 3): a relative
    # tolerance of 1e-6 below a power of two keeps the smaller exponent.
    exp = max(0, math.ceil(math.log2(half * (1 - 1e-6)))) if half > 0 else 0
    scale = 32768.0 / (2.0**exp)
    q = np.round((xyz.astype(np.float64) - offset.astype(np.float64)) * scale)
    return offset, exp, np.clip(q, -32768, 32767).astype(">i2")


def _binormal(sign: np.ndarray) -> np.ndarray:
    return np.where(sign < 0, -32768, 32767).astype(">i2")


def surface_streams(
    verts: np.ndarray, pc_flags: int, quantise_positions: bool = True
) -> tuple[int, bytes, bytes, bytes, int]:
    """PS3 (flags, verts0, vertex stream, tail 0x48..0x5c, constant colour word) of one
    surface from its PC vertices."""
    n = len(verts)
    colours = verts["colour"]
    constant = n > 0 and bool(np.all(colours == colours[0]))
    flags = pc_flags & ~(FLAG_QUANTISED | FLAG_CONSTANT_COLOUR)
    if quantise_positions:
        flags |= FLAG_QUANTISED
    if constant and quantise_positions:
        # formats 4 and 6 (float positions, constant colour) load no vertex stream at all
        # (structs-map.md 9), so an unquantised surface keeps its colours.
        flags |= FLAG_CONSTANT_COLOUR
    else:
        constant = False
    # PC colours are D3DCOLOR bytes B, G, R, A; PS3 stream colours R, G, B, A (all 67
    # varying-colour surfaces) and the constant colour word 0xAARRGGBB (the PC u32 as is,
    # big-endian: PC bfbfbfff -> ffbfbfbf, 4 surfaces).
    colour_word = struct.unpack("<I", bytes(colours[0]))[0] if constant else 0
    colours = colours[:, [2, 1, 0, 3]]
    normal = cmp_pack(pc_unit_vectors(verts["normal"]))
    tangent = cmp_pack(pc_unit_vectors(verts["tangent"]))
    uv = verts["uv"].astype(">u4")
    fmt = flags & 7
    tail = bytearray(PS3_XSURFACE - 0x48)
    if quantise_positions:
        offset, exp, q = quantise(verts["xyz"])
        pos = np.empty((n, 4), ">i2")
        pos[:, :3] = q
        pos[:, 3] = _binormal(verts["binormal_sign"])
        struct.pack_into(">3f", tail, 0, *offset.tolist())
        tail[0xC] = QUANTISED_MARK
        tail[0xD:0x10] = bytes([exp, exp, exp])
        if fmt in (3, 7):
            rec = np.empty(n, [("p", ">i2", 4), ("n", ">u4"), ("t", ">u4")])
            rec["p"], rec["n"], rec["t"] = pos, normal, tangent
            verts0 = rec.tobytes()
        else:
            verts0 = pos.tobytes()
    else:
        rec = np.empty(n, [("p", ">f4", 3), ("s", ">f4")])
        rec["p"], rec["s"] = verts["xyz"], verts["binormal_sign"]
        verts0 = rec.tobytes()
    struct.pack_into(">I", tail, 0x10, colour_word)
    if fmt in (0, 1, 2):
        rec = np.empty(n, [("n", ">u4"), ("t", ">u4"), ("uv", ">u4"), ("c", "u1", 4)])
        rec["n"], rec["t"], rec["uv"], rec["c"] = normal, tangent, uv, colours
    elif fmt == 5:
        rec = np.empty(n, [("n", ">u4"), ("t", ">u4"), ("uv", ">u4")])
        rec["n"], rec["t"], rec["uv"] = normal, tangent, uv
    elif fmt == 3:
        rec = np.empty(n, [("uv", ">u4"), ("c", "u1", 4)])
        rec["uv"], rec["c"] = uv, colours
    elif fmt == 7:
        rec = uv
    else:
        raise ConvertError(f"XSurface flags {flags:#x}: format {fmt} has no stream rule")
    return flags, verts0, rec.tobytes(), bytes(tail), colour_word


def _target(fetch: Fetch | None, raw: int):
    target = getattr(fetch, "target", None)
    found = target(raw) if target is not None else None
    if found is None or found.kind != "data":
        raise ConvertError(f"offset pointer {raw:#010x}: names no loaded data")
    return found


def _shared_list(fetch: Fetch | None, raw: int, count: int) -> list:
    """The elements of a list of structs an offset pointer names (shared vertList)."""
    t = _target(fetch, raw)
    data = t.node[t.key]
    if not isinstance(data, list) or t.within:
        raise ConvertError(f"offset pointer {raw:#010x}: not the start of a struct list")
    return data[t.index or 0 : (t.index or 0) + count]


def _shared_node(fetch: Fetch | None, raw: int) -> dict:
    """The node an offset pointer names (a shared collision tree: its "raw" header)."""
    t = _target(fetch, raw)
    if t.key != "raw" or t.within:
        raise ConvertError(f"offset pointer {raw:#010x}: not the start of a struct")
    return t.node


def _inline(data: bytes | None) -> int:
    return PTR_INLINE if data else 0


def _pc_data(surface: dict, key: str, raw: int, size: int, fetch: Fetch | None) -> bytes | None:
    """A PC surface array: inline bytes, or the bytes an offset pointer names."""
    value = surface.get(key)
    if value is not None:
        return bytes(value)
    if raw in (0,):
        return None
    if fetch is None:
        raise ConvertError(f"XSurface {key}: offset pointer {raw:#010x} and no fetch")
    return fetch(raw, size)


def convert_surface(pc_surface: dict, fetch: Fetch | None = None, quantise_positions=True) -> dict:
    """One PC XSurface node -> a PS3 XSurface node (all data inline)."""
    raw = bytes(pc_surface["raw"])
    if len(raw) != PC_XSURFACE:
        raise ConvertError(f"PC XSurface: expected {PC_XSURFACE} bytes, found {len(raw)}")
    pc_flags = struct.unpack_from("<H", raw, 2)[0]
    vert_count = struct.unpack_from("<H", raw, 4)[0]
    tri_count = struct.unpack_from("<H", raw, 6)[0]
    blend_counts = struct.unpack_from("<4h", raw, 0x10)
    v = blend_counts
    verts_pc = _pc_data(pc_surface, "verts0", _u32(raw, 0x20), 32 * vert_count, fetch)
    tris = _pc_data(pc_surface, "tri_indices", _u32(raw, 0xC), 6 * tri_count, fetch)
    blend = _pc_data(
        pc_surface,
        "verts_blend",
        _u32(raw, 0x18),
        2 * (v[0] + 3 * v[1] + 5 * v[2] + 7 * v[3]),
        fetch,
    )
    tension = _pc_data(pc_surface, "tension_data", _u32(raw, 0x1C), 48 * sum(v), fetch)
    verts = np.frombuffer(verts_pc or b"", PC_PACKED_VERTEX)
    flags, verts0, stream, tail, _ = surface_streams(verts, pc_flags, quantise_positions)

    lists_out = None
    lists = pc_surface.get("vert_lists")
    list_count = raw[1]
    if lists is None and _u32(raw, 0x28) not in (0,) and list_count:
        if fetch is None:
            raise ConvertError("XSurface vertList: offset pointer and no fetch")
        lists = _shared_list(fetch, _u32(raw, 0x28), list_count)
    if lists is not None:
        lists_out = []
        for element in lists:
            rec = bytearray(swap_struct("XRigidVertList", element["raw"]))
            tree = element.get("collision_tree")
            out = {"_t": "XRigidVertList"}
            if tree is None and struct.unpack_from("<I", element["raw"], 8)[0] not in (0,):
                tree = _shared_node(fetch, struct.unpack_from("<I", element["raw"], 8)[0])
            if tree is not None:
                head = swap_struct("XSurfaceCollisionTree", tree["raw"])
                t = {"_t": "XSurfaceCollisionTree", "raw": head}
                t["nodes"] = swap_struct("u16", tree["nodes"]) if tree.get("nodes") else None
                t["leafs"] = swap_struct("u16", tree["leafs"]) if tree.get("leafs") else None
                out["collision_tree"] = t
                struct.pack_into(">I", rec, 8, PTR_INLINE)
            else:
                out["collision_tree"] = None
            out["raw"] = bytes(rec)
            lists_out.append(out)

    rec = bytearray(PS3_XSURFACE)
    rec[0] = raw[0]
    rec[1] = list_count
    struct.pack_into(">HHH", rec, 2, flags, vert_count, tri_count)
    struct.pack_into(">I", rec, 0x8, _inline(tris))
    struct.pack_into(">4h", rec, 0xC, *blend_counts)
    struct.pack_into(">I", rec, 0x14, _inline(blend))
    struct.pack_into(">I", rec, 0x18, _inline(tension))
    struct.pack_into(">I", rec, 0x1C, _inline(verts0))
    struct.pack_into(">I", rec, 0x24, _inline(stream))
    struct.pack_into(">I", rec, 0x2C, PTR_INLINE if lists_out else 0)
    rec[0x34:0x48] = _swap32(raw[0x30:0x44])
    rec[0x48:0x5C] = tail
    return {
        "_t": "XSurface",
        "raw": bytes(rec),
        "verts_blend": swap_struct("u16", blend) if blend else None,
        "tension_data": _swap32(tension) if tension else None,
        "verts0": verts0 or None,
        "vertex_stream": stream or None,
        "vert_lists": lists_out,
        "tri_indices": swap_struct("u16", tris) if tris else None,
    }


def _swap32(data: bytes) -> bytes:
    return np.frombuffer(data, "<u4").astype(">u4").tobytes()


def _brush_wrapper(raw: bytes) -> bytes:
    """BrushWrapper (0x60): cbrush_t's fields plus the planes pointer at +0x5c."""
    return swap_struct("cbrush_t", raw[:0x60])[:0x5C] + _swap32(raw[0x5C:0x60])


def _collmap(pc_collmap: dict) -> dict:
    """Collmap -> PhysGeomList -> PhysGeomInfo -> BrushWrapper: same layouts, swapped."""
    out: dict = {"_t": "Collmap", "raw": pc_collmap["raw"]}
    geom_list = pc_collmap.get("geom_list")
    out["geom_list"] = swap_struct("PhysGeomList", geom_list) if geom_list else None
    geoms = []
    for g in pc_collmap.get("geoms") or ():
        element: dict = {"_t": "PhysGeomInfo", "raw": swap_struct("PhysGeomInfo", g["raw"])}
        brush = g.get("brush")
        if brush is not None:
            b: dict = {"_t": "BrushWrapper", "raw": _brush_wrapper(brush["raw"])}
            sides = []
            for side in brush.get("sides") or ():
                if side.get("plane") is None:
                    raise ConvertError("BrushWrapper side: shared plane not supported")
                sides.append(
                    {
                        "_t": "cbrushside_t",
                        "raw": swap_struct("cbrushside_t", side["raw"]),
                        "plane": swap_struct("cplane_s", side["plane"]),
                    }
                )
            b["sides"] = sides or None
            b["verts"] = swap_struct("vec3", brush["verts"]) if brush.get("verts") else None
            if brush.get("planes"):
                raise ConvertError("BrushWrapper planes inline: the PS3 loader does not load them")
            element["brush"] = b
        else:
            element["brush"] = None
        geoms.append(element)
    out["geoms"] = geoms if pc_collmap.get("geoms") is not None else None
    return out


def convert_xmodel(
    pc_model: dict,
    fetch: Fetch | None = None,
    bone_name: Callable[[int], int] | None = None,
) -> ModelResult:
    """A parsed PC XModel node -> a PS3 XModel node (``xfile/handlers/xmodel.py`` keys).

    ``bone_name`` maps a PC script string index to the target zone's (identity when
    None). Materials and the physPreset are carried as parsed (nodes or links); the
    caller decides what they become in the target zone."""
    notes: list[str] = []
    pc_header = bytes(pc_model["header"])
    header = bytearray(xmodel_header(pc_header))
    bones, roots, surf_count = pc_header[4], pc_header[5], pc_header[6]
    out: dict = {"_t": "XModel", "name": pc_model.get("name")}

    def data(key: str, off: int, size: int) -> bytes | None:
        value = pc_model.get(key)
        if value is not None:
            return bytes(value)
        raw = _u32(pc_header, off)
        if raw == 0 or size == 0:
            return None
        if fetch is None:
            raise ConvertError(f"XModel {out['name']}: {key} is an offset pointer and no fetch")
        struct.pack_into(">I", header, off, PTR_INLINE)
        return fetch(raw, size)

    names = data("bone_names", 0x8, 2 * bones)
    if names is not None:
        idx = np.frombuffer(names, "<u2")
        if bone_name is not None:
            idx = np.array([bone_name(int(i)) for i in idx], dtype=np.uint16)
        out["bone_names"] = idx.astype(">u2").tobytes()
    else:
        out["bone_names"] = None
    out["parent_list"] = data("parent_list", 0xC, bones - roots)
    quats = data("quats", 0x10, 8 * (bones - roots))
    out["quats"] = swap_struct("u16", quats) if quats else None
    trans = data("trans", 0x14, 16 * (bones - roots))
    out["trans"] = _swap32(trans) if trans else None
    out["part_classification"] = data("part_classification", 0x18, bones)
    base_mat = data("base_mat", 0x1C, 0x20 * bones)
    out["base_mat"] = _swap32(base_mat) if base_mat else None
    surfs = pc_model.get("surfs")
    out["surfs"] = [convert_surface(s, fetch) for s in surfs] if surfs is not None else None
    if surfs is not None and len(surfs) != surf_count:
        raise AssertionError((len(surfs), surf_count))
    materials = pc_model.get("materials")
    out["materials"] = (
        [
            {"_t": "XModelMaterial", "raw": _swap32(m["raw"]), "material": m.get("material")}
            for m in materials
        ]
        if materials is not None
        else None
    )
    coll = pc_model.get("coll_surfs")
    if coll is not None:
        rows = []
        for c in coll:
            sw = swap_struct("XModelCollSurf_s", c["raw"])
            rows.append(sw[8:0x2C])
        out["coll_surfs"] = b"".join(rows)
        if any(c.get("coll_tris") for c in coll):
            notes.append(
                f"{sum(1 for c in coll if c.get('coll_tris'))} collision surfaces carry "
                "collTris, which the PS3 struct has no field for (dropped)"
            )
    else:
        out["coll_surfs"] = None
    bone_info = pc_model.get("bone_info")
    out["bone_info"] = swap_struct("XBoneInfo", bone_info) if bone_info else None
    mips = pc_model.get("high_mip_bounds")
    out["high_mip_bounds"] = swap_struct("XModelHighMipBounds", mips) if mips else None
    preset = pc_model.get("phys_preset")
    if isinstance(preset, dict):
        preset = dict(preset)
        preset["_t"] = "PhysPreset"
        preset["header"] = swap_struct("PhysPreset", preset["header"])
    out["phys_preset"] = preset
    collmaps = pc_model.get("collmaps")
    out["collmaps"] = [_collmap(c) for c in collmaps] if collmaps is not None else None
    if pc_model.get("phys_constraints") is not None:
        raise ConvertError(f"XModel {out['name']}: physConstraints not supported")
    out["phys_constraints"] = None
    struct.pack_into(">I", header, 0xE0, ps3_mem_usage(_u32(pc_header, 0xE0), surfs, out["surfs"]))
    out["header"] = bytes(header)
    return ModelResult(out, notes)


def ps3_mem_usage(pc_mem_usage: int, pc_surfs: list | None, ps3_surfs: list | None) -> int:
    """PS3 memUsage (+0xe0) from the PC one (+0xe0): PC - 4 (header 0xf8 vs 0xfc), then for
    each surface whose PC vertices are its own (not an offset pointer to another
    surface's): + 24 (XSurface 0x5c vs 0x44) + vertCount x (PS3 bytes per vertex - 32).
    Exact for 288 of the 289 mp_nuked models with surfaces; the other is the one surface
    PS3 leaves unquantised (mp_flag_american_vertical, +1440 = 180 vertices x 8)."""
    if pc_surfs is None or ps3_surfs is None:  # surfaces in another zone (name ",...")
        return pc_mem_usage
    total = pc_mem_usage - 4
    for pc_surface, s in zip(pc_surfs, ps3_surfs, strict=True):
        if pc_surface.get("verts0") is None:
            continue
        flags, n = struct.unpack_from(">HH", s["raw"], 2)
        v0, stream = _stream_layout(flags)
        total += 24 + n * (v0 + stream - 32)
    return total


# -- comparison with a PS3 zone holding the same models ---------------------------------------


def fetcher(xfile) -> Fetch:
    """A Fetch over a parsed zone: the bytes an offset pointer names (``XFile.resolve``)."""

    def fetch(raw: int, size: int) -> bytes:
        target = xfile.resolve(raw)
        if target is None or target.kind != "data":
            raise ConvertError(f"offset pointer {raw:#010x}: names no loaded data")
        data = target.node[target.key]
        start = target.within
        if isinstance(data, list):
            start += sum(len(e["raw"]) for e in data[: target.index or 0])
            data = b"".join(e["raw"] for e in data)
        return bytes(data)[start : start + size]

    fetch.target = xfile.resolve  # type: ignore[attr-defined]
    return fetch


def _cmp_unit(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Angle in degrees between CMP words a and b (big-endian u32 arrays)."""

    def unpack(w: np.ndarray) -> np.ndarray:
        w = w.astype(np.int64)
        x = ((w & 0x7FF) ^ 0x400) - 0x400
        y = (((w >> 11) & 0x7FF) ^ 0x400) - 0x400
        z = (((w >> 22) & 0x3FF) ^ 0x200) - 0x200
        v = np.stack([x / 1023.0, y / 1023.0, z / 511.0], axis=1)
        n = np.linalg.norm(v, axis=1, keepdims=True)
        return v / np.maximum(n, 1e-9)

    dot = np.clip(np.sum(unpack(a) * unpack(b), axis=1), -1, 1)
    return np.degrees(np.arccos(dot))


def _ps3_data(surface: dict, key: str, off: int, size: int, fetch: Fetch) -> bytes | None:
    value = surface.get(key)
    if value is not None:
        return bytes(value)
    raw = _u32(surface["raw"], off, ">I")
    if raw == 0 or size == 0:
        return None
    return fetch(raw, size)


def _stream_layout(flags: int) -> tuple[int, int]:
    """(verts0 bytes, stream bytes) per vertex for PS3 flags."""
    v0 = 16 if flags & 1 == 0 else (8 if flags & 3 == 1 else 16)
    return v0, {0: 16, 1: 16, 2: 16, 3: 8, 5: 12, 7: 4}.get(flags & 7, 0)


def _decode_ps3(flags: int, verts0: bytes, stream: bytes, n: int) -> dict:
    """PS3 vertices -> arrays: q (s16 x 3) or xyz, sign, normal, tangent, uv, colour."""
    out: dict = {}
    if flags & 1 == 0:
        a = np.frombuffer(verts0, ">f4").reshape(n, 4)
        out["xyz"], out["sign"] = a[:, :3], a[:, 3]
    else:
        stride = 8 if flags & 3 == 1 else 16
        raw = np.frombuffer(verts0, np.uint8).reshape(n, stride)
        q = raw[:, :8].copy().view(">i2").reshape(n, 4)
        out["q"], out["sign"] = q[:, :3], q[:, 3]
        if stride == 16:
            nt = raw[:, 8:16].copy().view(">u4").reshape(n, 2)
            out["normal"], out["tangent"] = nt[:, 0], nt[:, 1]
    fmt = flags & 7
    s = np.frombuffer(stream, np.uint8)
    if fmt in (0, 1, 2, 5):
        width = 16 if fmt != 5 else 12
        s = s.reshape(n, width)
        out["normal"] = s[:, 0:4].copy().view(">u4")[:, 0]
        out["tangent"] = s[:, 4:8].copy().view(">u4")[:, 0]
        out["uv"] = s[:, 8:12].copy().view(">u4")[:, 0]
        if fmt != 5:
            out["colour"] = s[:, 12:16]
    elif fmt == 3:
        s = s.reshape(n, 8)
        out["uv"] = s[:, 0:4].copy().view(">u4")[:, 0]
        out["colour"] = s[:, 4:8]
    elif fmt == 7:
        out["uv"] = s.reshape(n, 4).copy().view(">u4")[:, 0]
    return out


#: Header byte ranges compared as data (pointers, memUsage excluded).
_HEADER_DATA = (
    (0x4, 0x8),
    (0x28, 0xA0),
    (0xA4, 0xAC),
    (0xB0, 0xD0),
    (0xD4, 0xE0),
    (0xE4, 0xE8),
    (0xEC, 0xF0),
)


def compare_xmodels(pc_xfile, ps3_xfile, pc_models: dict, ps3_models: dict) -> dict:
    """Convert every PC model whose name the PS3 zone also has and compare it with the PS3
    one field by field and vertex by vertex. Returns counts (docs/convert.md 12)."""
    pc_fetch, ps3_fetch = fetcher(pc_xfile), fetcher(ps3_xfile)
    pc_strings, ps3_strings = pc_xfile.script_strings, ps3_xfile.script_strings
    r: dict = {"models": 0, "surfaces": 0, "vertices": 0, "triangles": 0}
    diffs: dict[str, int] = {}
    worst: dict[str, float] = {"normal_deg": 0.0, "tangent_deg": 0.0, "position_steps": 0.0}
    hist = np.zeros(4, np.int64)  # position error in steps: 0, <=1, <=2, more

    def bad(key: str, n: int = 1) -> None:
        diffs[key] = diffs.get(key, 0) + n

    for name in sorted(set(pc_models) & set(ps3_models)):
        a, b = pc_models[name], ps3_models[name]
        res = convert_xmodel(a, pc_fetch, None).node
        r["models"] += 1
        ha, hb = res["header"], bytes(b["header"])
        for lo, hi in _HEADER_DATA:
            if ha[lo:hi] != hb[lo:hi]:
                bad(f"header {lo:#x}..{hi:#x}")
        if ha[0xE0:0xE4] != hb[0xE0:0xE4]:
            bad("header memUsage")
        bn_a = res["bone_names"] and np.frombuffer(res["bone_names"], ">u2")
        bn_b = b.get("bone_names")
        if bn_b is None and _u32(hb, 0x8, ">I") not in (0,):
            bn_b = ps3_fetch(_u32(hb, 0x8, ">I"), 2 * hb[4])
        if bn_a is not None and bn_b is not None:
            names_a = [pc_strings[i] for i in bn_a]
            names_b = [ps3_strings[i] for i in np.frombuffer(bytes(bn_b), ">u2")]
            if names_a != names_b:
                bad("bone names")
        for key, off, size in (
            ("parent_list", 0xC, hb[4] - hb[5]),
            ("quats", 0x10, 8 * (hb[4] - hb[5])),
            ("trans", 0x14, 16 * (hb[4] - hb[5])),
            ("part_classification", 0x18, hb[4]),
            ("base_mat", 0x1C, 0x20 * hb[4]),
            ("coll_surfs", 0xA0, 0x24 * _u32(hb, 0xA4, ">I")),
            ("bone_info", 0xAC, 0x2C * hb[4]),
            ("high_mip_bounds", 0xD0, 0x10 * hb[6]),
        ):
            theirs = b.get(key)
            if theirs is None and _u32(hb, off, ">I") not in (0,) and size:
                theirs = ps3_fetch(_u32(hb, off, ">I"), size)
            mine = res.get(key)
            if (mine or b"") != (bytes(theirs) if theirs is not None else b""):
                bad(key)
        mats_a = [_name(m.get("material")) for m in res["materials"] or ()]
        mats_b = [_name(m.get("material")) for m in b.get("materials") or ()]
        if mats_a != mats_b:
            bad("material names")
        pa, pb = res.get("phys_preset"), b.get("phys_preset")
        if isinstance(pa, dict) and isinstance(pb, dict):
            if (
                pa["header"][4:0x1C] + pa["header"][0x20:]
                != bytes(pb["header"])[4:0x1C] + bytes(pb["header"])[0x20:]
            ):
                bad("physPreset")
        elif _name(pa) != _name(pb):
            bad("physPreset name")
        if _collmaps_bytes(res.get("collmaps")) != _collmaps_bytes(b.get("collmaps")):
            bad("collmaps")
        for sa, sb in zip(res["surfs"] or (), b.get("surfs") or (), strict=True):
            _compare_surface(sa, sb, ps3_fetch, r, bad, worst, hist)
    r["differences"] = dict(sorted(diffs.items()))
    r["worst"] = worst
    r["position_error_steps"] = {
        "0": int(hist[0]),
        "<=1": int(hist[1]),
        "<=2": int(hist[2]),
        ">2": int(hist[3]),
    }
    return r


def _name(obj) -> str | None:
    if isinstance(obj, dict):
        return obj.get("name")
    return getattr(obj, "name", None)


def _collmaps_bytes(collmaps) -> bytes:
    out = b""
    for c in collmaps or ():
        out += bytes(c.get("geom_list") or b"")[:4] + bytes(c.get("geom_list") or b"")[8:]
        for g in c.get("geoms") or ():
            out += bytes(g["raw"])[4:]
            brush = g.get("brush")
            if brush:
                raw = bytes(brush["raw"])
                out += raw[:0x20] + raw[0x24:0x58]
                for side in brush.get("sides") or ():
                    out += bytes(side["raw"])[4:] + bytes(side.get("plane") or b"")
                out += bytes(brush.get("verts") or b"")
    return out


def _compare_surface(sa, sb, fetch, r, bad, worst, hist) -> None:
    ra, rb = sa["raw"], bytes(sb["raw"])
    r["surfaces"] += 1
    fa, fb = struct.unpack_from(">H", ra, 2)[0], struct.unpack_from(">H", rb, 2)[0]
    n = struct.unpack_from(">H", rb, 4)[0]
    tri = struct.unpack_from(">H", rb, 6)[0]
    r["vertices"] += n
    r["triangles"] += tri
    for lo, hi, what in (
        (0, 2, "surface tileMode, vertListCount"),
        (4, 8, "surface counts"),
        (0xC, 0x14, "surface vertInfo counts"),
        (0x34, 0x48, "surface partBits"),
        (0x48, 0x54, "surface posOffset"),
        (0x54, 0x58, "surface +0x54 and exponents"),
        (0x58, 0x5C, "surface constant colour"),
    ):
        if ra[lo:hi] != rb[lo:hi]:
            bad(what)
    if fa != fb:
        bad("surface flags")
        return
    v0, st = _stream_layout(fb)
    mine = _decode_ps3(fa, sa["verts0"] or b"", sa["vertex_stream"] or b"", n)
    theirs = _decode_ps3(
        fb,
        _ps3_data(sb, "verts0", 0x1C, v0 * n, fetch) or b"",
        _ps3_data(sb, "vertex_stream", 0x24, st * n, fetch) or b"",
        n,
    )
    if "q" in mine:
        d = np.abs(mine["q"].astype(np.int64) - theirs["q"].astype(np.int64)).max(axis=1)
        hist[0] += int(np.sum(d == 0))
        hist[1] += int(np.sum(d == 1))
        hist[2] += int(np.sum(d == 2))
        hist[3] += int(np.sum(d > 2))
        if n:
            worst["position_steps"] = max(worst["position_steps"], float(d.max()))
    elif not np.array_equal(mine["xyz"], theirs["xyz"]):
        bad("float positions")
    if not np.array_equal(mine["sign"], theirs["sign"]):
        bad("binormal sign")
    for key in ("normal", "tangent"):
        if n and key in mine:
            same = mine[key] == theirs[key]
            r[f"{key}_exact"] = r.get(f"{key}_exact", 0) + int(same.sum())
            if not same.all():
                worst[f"{key}_deg"] = max(
                    worst[f"{key}_deg"], float(_cmp_unit(mine[key], theirs[key]).max())
                )
    if not np.array_equal(mine.get("uv"), theirs.get("uv")):
        bad("uv")
    if "colour" in mine and not np.array_equal(mine["colour"], theirs["colour"]):
        bad("colour")
    tris = _ps3_data(sb, "tri_indices", 0x8, 6 * tri, fetch)
    if (sa["tri_indices"] or b"") != (tris or b""):
        bad("triangle indices")
    for key, off in (("verts_blend", 0x14), ("tension_data", 0x18)):
        mine_b = sa.get(key)
        if mine_b is None:
            continue
        theirs_b = _ps3_data(sb, key, off, len(mine_b), fetch)
        if mine_b != theirs_b:
            bad(key)
    la, lb = sa.get("vert_lists") or [], sb.get("vert_lists")
    if lb is None and rb[1] and _u32(rb, 0x2C, ">I"):
        lb = [
            {"raw": fetch(_u32(rb, 0x2C, ">I"), 12 * rb[1])[12 * i : 12 * i + 12]}
            for i in range(rb[1])
        ]
    for x, y in zip(la, lb or (), strict=False):
        if bytes(x["raw"])[:8] != bytes(y["raw"])[:8]:
            bad("rigid vert list")
        tx, ty = x.get("collision_tree"), y.get("collision_tree")
        if tx and ty:
            if tx["raw"][:0x18] + tx["raw"][0x18:0x1C] + tx["raw"][0x20:0x24] != (
                bytes(ty["raw"])[:0x1C] + bytes(ty["raw"])[0x20:0x24]
            ):
                bad("collision tree header")
            if (tx.get("nodes") or b"") != bytes(ty.get("nodes") or b"") or (
                tx.get("leafs") or b""
            ) != bytes(ty.get("leafs") or b""):
                bad("collision tree nodes, leafs")


# -- binding a converted model to a PS3 zone's assets -----------------------------------------


def asset_words(xfile, kind: str) -> dict[str, tuple[bytes, Any]]:
    """Asset name -> (alias word, node) for every asset of node kind ``kind`` (``"XModel"``,
    ``"Material"``, ``"PhysPreset"``) that a parsed zone holds behind an alias slot."""
    out: dict[str, tuple[bytes, Any]] = {}
    for key, (node, _) in sorted(xfile.refs.slots.items()):
        if isinstance(node, dict) and node.get("_t") == kind and node.get("name"):
            out.setdefault(node["name"], (struct.pack(">I", key + 1), node))
    return out


def bind(model: dict, materials: dict[str, tuple[bytes, Any]], presets: dict) -> None:
    """Point a converted model's materials (and physPreset) at a PS3 zone's assets of the
    same name (``asset_words``); a name the zone lacks stops with that name."""
    for element in model.get("materials") or ():
        name = _name(element.get("material"))
        if name not in materials:
            raise ConvertError(f"XModel {model.get('name')}: material {name!r} not in the zone")
        element["raw"], element["material"] = materials[name]
    preset = model.get("phys_preset")
    if preset is not None:
        name = _name(preset)
        if name not in presets:
            raise ConvertError(f"XModel {model.get('name')}: physPreset {name!r} not in the zone")
        header = bytearray(model["header"])
        header[0xE8:0xEC] = presets[name][0]
        model["header"] = bytes(header)
        model["phys_preset"] = presets[name][1]


def adopt(model: dict, stock: dict) -> dict:
    """Replace a stock PS3 model by a converted one in place and return the stock dict,
    now holding the converted model. The stock dict, its material elements and its
    physPreset are kept: in a PS3 zone the first model using a material loads it inline,
    and other assets' alias pointers name the fields of that model's ``materials`` array
    (identities are by node, docs/research/remap.md 8). Material names must agree surface
    by surface."""
    mine = [_name(m.get("material")) for m in model.get("materials") or ()]
    theirs = [_name(m.get("material")) for m in stock.get("materials") or ()]
    if mine != theirs:
        raise ConvertError(f"XModel {model.get('name')}: materials {mine} vs stock {theirs}")
    # collmaps: each BrushWrapper's planes (+0x5c) is an offset pointer to its first
    # side's plane on both platforms, which only the stock nodes can name; the converted
    # collmaps equal the stock ones in every other byte (compare_xmodels).
    keep = {k: stock.get(k) for k in ("materials", "phys_preset", "collmaps")}
    header = bytearray(model["header"])
    header[0xE8:0xF4] = bytes(stock["header"])[0xE8:0xF4]
    surfs = stock.get("surfs")
    if surfs is not None and model.get("surfs") is not None and len(surfs) == len(model["surfs"]):
        # Surfaces too keep their dicts: PS3 zones share vertex, index and collision data
        # between models by offset pointer.
        for old, new in zip(surfs, model["surfs"], strict=True):
            _in_place(old, new)
        model = {**model, "surfs": surfs}
    stock.clear()
    stock.update(model)
    stock.update(keep)
    stock["header"] = bytes(header)
    return stock


def _in_place(old: dict, new: dict) -> None:
    lists_old, lists_new = old.get("vert_lists"), new.get("vert_lists")
    if lists_old and lists_new and len(lists_old) == len(lists_new):
        for a, b in zip(lists_old, lists_new, strict=True):
            tree_a, tree_b = a.get("collision_tree"), b.get("collision_tree")
            if isinstance(tree_a, dict) and isinstance(tree_b, dict):
                tree_a.clear()
                tree_a.update(tree_b)
                b = {**b, "collision_tree": tree_a}
            a.clear()
            a.update(b)
        new = {**new, "vert_lists": lists_old}
    old.clear()
    old.update(new)
