"""Original blocky pixel-art textures, generated by code (numpy only).

Each tile is drawn as a small (default 16x16) RGBA array and upscaled with nearest-neighbour
to the size the engine wants, so the pixels stay crisp. These are this project's own art: no
external image is read, traced or copied. ``render`` gives one tile; ``encode_ps3`` DXT-encodes
it through :mod:`opent5.formats.texture`; ``preview_png`` writes a PNG to look at. See
docs/mapgen.md and docs/research/textures.md.
"""

from __future__ import annotations

import numpy as np

from opent5.formats import texture as tx

#: Tiles the map uses; grass and log have a top and a side variant.
TILE_NAMES = (
    "grass_top",
    "grass_side",
    "dirt",
    "stone",
    "sand",
    "plank",
    "log_side",
    "log_top",
    "leaves",
    "water",
    "cobble",
    "lava",
)

BASE = 16  # native pixel-art resolution


def _rng(name: str, seed: int) -> np.random.Generator:
    h = seed & 0xFFFFFFFF
    for c in name.encode():
        h = (h * 131 + c) & 0xFFFFFFFF
    return np.random.default_rng(h)


def _fill(h: int, w: int, rgb: tuple[int, int, int], a: int = 255) -> np.ndarray:
    t = np.empty((h, w, 4), np.uint8)
    t[..., 0], t[..., 1], t[..., 2], t[..., 3] = (*rgb, a)
    return t


def _speckle(t: np.ndarray, rng: np.random.Generator, amp: int) -> None:
    n = rng.integers(-amp, amp + 1, size=t.shape[:2] + (1,))
    t[..., :3] = np.clip(t[..., :3].astype(np.int16) + n, 0, 255).astype(np.uint8)


def _grass_top(seed):
    rng = _rng("grass_top", seed)
    t = _fill(BASE, BASE, (86, 141, 54))
    _speckle(t, rng, 16)
    # scattered brighter blades and a few darker tufts
    for _ in range(26):
        y, x = rng.integers(0, BASE, 2)
        t[y, x, :3] = (118, 176, 70)
    for _ in range(10):
        y, x = rng.integers(0, BASE, 2)
        t[y, x, :3] = (58, 104, 38)
    return t


def _dirt(seed):
    rng = _rng("dirt", seed)
    t = _fill(BASE, BASE, (123, 86, 57))
    _speckle(t, rng, 18)
    for _ in range(14):  # small dark clumps
        y, x = rng.integers(0, BASE - 1, 2)
        t[y : y + 2, x : x + 1, :3] = (92, 62, 40)
    return t


def _grass_side(seed):
    t = _dirt(seed)  # dirt body
    rng = _rng("grass_side", seed)
    green = (86, 141, 54)
    dark = (64, 110, 40)
    t[0:3, :, :3] = green
    t[0, :, :3] = dark  # a slightly darker lip at the very top
    _speckle(t[0:3], rng, 14)
    # jagged grass fringe dripping into the dirt on row 3-4
    for x in range(BASE):
        drip = rng.integers(0, 3)
        t[3 : 3 + drip, x, :3] = green
    return t


def _stone(seed):
    rng = _rng("stone", seed)
    t = _fill(BASE, BASE, (130, 130, 134))
    _speckle(t, rng, 14)
    for _ in range(3):  # darker cracks
        x = rng.integers(2, BASE - 2)
        y = rng.integers(0, BASE // 2)
        length = rng.integers(4, 9)
        for d in range(length):
            yy = min(BASE - 1, y + d)
            xx = min(BASE - 1, x + rng.integers(-1, 2))
            t[yy, xx, :3] = (92, 92, 97)
    return t


def _sand(seed):
    rng = _rng("sand", seed)
    t = _fill(BASE, BASE, (221, 203, 140))
    _speckle(t, rng, 10)
    for _ in range(18):
        y, x = rng.integers(0, BASE, 2)
        t[y, x, :3] = (233, 218, 162)
    return t


def _plank(seed):
    rng = _rng("plank", seed)
    t = _fill(BASE, BASE, (150, 110, 66))
    shades = [(150, 110, 66), (138, 100, 58), (158, 118, 72), (144, 104, 62)]
    plank_h = 4
    for p, y0 in enumerate(range(0, BASE, plank_h)):
        t[y0 : y0 + plank_h, :, :3] = shades[p % len(shades)]
        t[y0, :, :3] = (96, 68, 40)  # seam line at the top of each plank
        # faint vertical grain
        for x in range(BASE):
            if rng.random() < 0.18:
                t[y0 : y0 + plank_h, x, :3] = np.clip(
                    np.array(shades[p % len(shades)]) - 12, 0, 255
                )
    _speckle(t, rng, 6)
    return t


def _log_side(seed):
    rng = _rng("log_side", seed)
    t = _fill(BASE, BASE, (106, 78, 48))
    for x in range(BASE):  # vertical bark streaks
        if rng.random() < 0.35:
            t[:, x, :3] = (84, 60, 36)
        elif rng.random() < 0.2:
            t[:, x, :3] = (124, 94, 60)
    _speckle(t, rng, 8)
    t[0, :, :3] = (150, 118, 80)  # lighter rim top
    t[-1, :, :3] = (150, 118, 80)
    return t


def _log_top(seed):
    rng = _rng("log_top", seed)
    t = _fill(BASE, BASE, (150, 118, 80))
    cy = cx = (BASE - 1) / 2
    yy, xx = np.mgrid[0:BASE, 0:BASE]
    r = np.sqrt((yy - cy) ** 2 + (xx - cx) ** 2)
    rings = np.sin(r * 1.5) * 0.5 + 0.5  # 0..1
    light = np.array([158, 126, 86])
    dark = np.array([118, 90, 58])
    col = (dark[None, None] + rings[..., None] * (light - dark)).astype(np.uint8)
    t[..., :3] = col
    t[int(cy), int(cx), :3] = (96, 70, 44)  # heart knot
    _speckle(t, rng, 6)
    return t


def _leaves(seed):
    rng = _rng("leaves", seed)
    t = _fill(BASE, BASE, (46, 96, 40))
    _speckle(t, rng, 18)
    for _ in range(40):  # mottled lighter and darker clusters
        y, x = rng.integers(0, BASE, 2)
        t[y, x, :3] = (72, 132, 56) if rng.random() < 0.6 else (28, 66, 28)
    return t


def _water(seed):
    rng = _rng("water", seed)
    t = _fill(BASE, BASE, (48, 92, 168), a=170)  # semi-transparent
    _speckle(t, rng, 8)
    for y in range(1, BASE, 4):  # horizontal wave highlights
        t[y, :, :3] = (78, 128, 196)
    return t


def _cobble(seed):
    rng = _rng("cobble", seed)
    t = _fill(BASE, BASE, (92, 92, 96))  # mortar background
    # irregular stones on a loose 4x4 grid, each a grey shade, leaving mortar gaps
    for gy in range(0, BASE, 4):
        for gx in range(0, BASE, 4):
            shade = rng.integers(110, 165)
            x0 = gx + rng.integers(0, 2)
            y0 = gy + rng.integers(0, 2)
            x1 = min(BASE, gx + rng.integers(3, 5))
            y1 = min(BASE, gy + rng.integers(3, 5))
            t[y0:y1, x0:x1, :3] = (shade, shade, shade + 4)
    _speckle(t, rng, 10)
    return t


def _lava(seed):
    rng = _rng("lava", seed)
    t = _fill(BASE, BASE, (210, 70, 20))  # molten orange body
    _speckle(t, rng, 22)
    # bright yellow-white hot cracks and a few darker crusted patches
    for _ in range(22):
        y, x = rng.integers(0, BASE, 2)
        t[y, x, :3] = (255, 208, 90)
    for _ in range(10):
        y, x = rng.integers(0, BASE - 1, 2)
        t[y : y + 2, x : x + 1, :3] = (120, 28, 12)
    for y in range(2, BASE, 5):  # glowing horizontal flow lines
        t[y, :, :3] = (255, 150, 40)
    return t


_DRAW = {
    "grass_top": _grass_top,
    "grass_side": _grass_side,
    "dirt": _dirt,
    "stone": _stone,
    "sand": _sand,
    "plank": _plank,
    "log_side": _log_side,
    "log_top": _log_top,
    "leaves": _leaves,
    "water": _water,
    "cobble": _cobble,
    "lava": _lava,
}


def base_tile(name: str, seed: int = 1) -> np.ndarray:
    """The native 16x16 RGBA pixel art of one tile."""
    if name not in _DRAW:
        raise KeyError(f"unknown tile {name!r}; expected one of {TILE_NAMES}")
    return _DRAW[name](seed)


def upscale(tile: np.ndarray, factor: int) -> np.ndarray:
    """Nearest-neighbour upscale (crisp pixels)."""
    return np.repeat(np.repeat(tile, factor, axis=0), factor, axis=1)


def render(name: str, px: int = 64, seed: int = 1) -> np.ndarray:
    """One tile at ``px`` x ``px``, nearest-neighbour upscaled from the 16x16 art."""
    if px % BASE:
        raise ValueError(f"px must be a multiple of {BASE}, found {px}")
    return upscale(base_tile(name, seed), px // BASE)


def has_alpha(rgba: np.ndarray) -> bool:
    return bool((rgba[..., 3] < 255).any())


def encode_ps3(rgba: np.ndarray) -> tuple[int, bytes]:
    """DXT-encode a tile (DXT1 opaque, DXT5 with alpha) with a full mip chain, PS3 stored
    bytes. Returns (GCM format code, stored bytes)."""
    fmt = tx.DXT45 if has_alpha(rgba) else tx.DXT1
    return fmt, tx.encode(rgba, fmt)


def preview_png(rgba: np.ndarray) -> bytes:
    return tx.write_png(rgba)
