"""Regenerate the zone inventory in docs/research/zones.md.

    .venv/bin/python tools/inventory.py                 # every zone in .env
    .venv/bin/python tools/inventory.py --also DIR ...  # plus other folders
    .venv/bin/python tools/inventory.py --no-recompress --json rows.json

Zones come from OPENT5_ZONES, OPENT5_PATCH_ZONES and OPENT5_DLC_ZONES (the
last searched recursively), so DLC appears as soon as .env points at it.
The table is written between the INVENTORY markers in zones.md; the rest of
that file is left alone.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from opent5 import env  # noqa: E402
from opent5.container import inventory  # noqa: E402

DOC = ROOT / "docs" / "research" / "zones.md"
START = "<!-- INVENTORY START -->"
END = "<!-- INVENTORY END -->"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--also", type=Path, nargs="*", default=[], help="extra zone folders")
    parser.add_argument("--no-recompress", action="store_true", help="skip the slow check")
    parser.add_argument("--jobs", type=int, default=4)
    parser.add_argument("--json", type=Path, help="also write the rows as JSON")
    parser.add_argument("--doc", type=Path, default=DOC)
    args = parser.parse_args(argv)

    roots = {}
    labels = {"OPENT5_ZONES": "disc", "OPENT5_PATCH_ZONES": "update", "OPENT5_DLC_ZONES": "dlc"}
    for key, label in labels.items():
        found = env.path_of(key)
        if found and found.is_dir():
            roots[label] = found
    paths = env.all_zones()
    for extra in args.also:
        update = roots.get("update")
        label = f"update-{extra.name}" if update and extra.parent == update.parent else extra.name
        roots[label] = extra
        paths += sorted(extra.glob("*.ff"))

    started = time.perf_counter()
    rows = inventory.run(paths, roots, recompress=not args.no_recompress, jobs=args.jobs)
    took = time.perf_counter() - started
    stats = inventory.summary(rows)
    stats["seconds"] = round(took)
    print(json.dumps(stats, indent=2))
    for row in rows:
        if row.error or row.odd_bodies:
            print(f"{row.folder}/{row.name}: {row.error or row.odd_bodies}")

    if args.json:
        args.json.write_text(json.dumps([asdict(r) for r in rows], indent=1) + "\n")
    block = (
        f"{START}\n\n"
        f"Generated by tools/inventory.py over {len(rows)} zones in {took:.0f} s "
        f"({args.jobs} processes).\n\n"
        + "".join(f"- {key.replace('_', ' ')}: {value}\n" for key, value in stats.items())
        + "\n"
        + "".join(f"- {r.folder}/{r.name}: {r.error}\n" for r in rows if r.error)
        + f"\n{inventory.render(rows)}\n{END}"
    )
    if args.doc.is_file() and START in args.doc.read_text():
        text = args.doc.read_text()
        before, rest = text.split(START, 1)
        after = rest.split(END, 1)[1] if END in rest else ""
        args.doc.write_text(before + block + after)
        print(f"updated {args.doc}")
    else:
        print(block)
    return 0 if not stats["errors"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
