"""PS3 (RSX / libgcm) texture data as T5 stores it, and conversion to and from DDS and PNG.

Pure numpy. See docs/research/textures.md for the evidence behind each rule.

Stored layout (one image):

    for each face (1, or 6 for a cube map, in +X -X +Y -Y +Z -Z order):
        for each mip level, largest first:
            the level's bytes, packed (no per-level padding)
        the face is padded to a multiple of 128 bytes
    the image's total is a multiple of 128 bytes

A level of a block-compressed format (DXT1/3/5) is the plain 4x4-block array, row-major
in blocks, each block in the same little-endian layout as a PC DDS. Uncompressed formats
without the LN flag (0x20) are swizzled: the texel at (x, y) lives at Morton index
interleave(x, y), x bit first. Texels of uncompressed formats are stored big-endian,
so A8R8G8B8 is the byte sequence A, R, G, B.

    decode(data, fmt, w, h, levels)  -> RGBA uint8 array (h, w, 4) of level 0
    encode(rgba, fmt, levels)        -> stored bytes, mips generated by a box filter
    read_dds / write_dds             -> DDS <-> (fmt, w, h, levels, faces, per-level bytes)
    read_png / write_png             -> 8-bit PNG <-> RGBA array
"""

from __future__ import annotations

import struct
import zlib
from dataclasses import dataclass, field

import numpy as np

# -- libgcm texture format codes (CELL_GCM_TEXTURE_*) --------------------------------------

B8 = 0x81
A1R5G5B5 = 0x82
A4R4G4B4 = 0x83
R5G6B5 = 0x84
A8R8G8B8 = 0x85
DXT1 = 0x86
DXT23 = 0x87
DXT45 = 0x88
G8B8 = 0x8B
DEPTH16 = 0x92
X16 = 0x94
Y16_X16 = 0x95
W16_Z16_Y16_X16_FLOAT = 0x9A
X32_FLOAT = 0x9C
D8R8G8B8 = 0x9E

#: Flag bits OR-ed into the format byte.
LN = 0x20  # linear (pitch) layout instead of swizzled
UN = 0x40  # unnormalised texture coordinates

FORMAT_NAMES = {
    B8: "B8",
    A1R5G5B5: "A1R5G5B5",
    A4R4G4B4: "A4R4G4B4",
    R5G6B5: "R5G6B5",
    A8R8G8B8: "A8R8G8B8",
    DXT1: "DXT1",
    DXT23: "DXT23",
    DXT45: "DXT45",
    G8B8: "G8B8",
    X16: "X16",
    Y16_X16: "Y16_X16",
    W16_Z16_Y16_X16_FLOAT: "W16_Z16_Y16_X16_FLOAT",
    X32_FLOAT: "X32_FLOAT",
    D8R8G8B8: "D8R8G8B8",
}

#: bytes per 4x4 block for compressed formats
BLOCK_BYTES = {DXT1: 8, DXT23: 16, DXT45: 16}
#: bytes per texel for uncompressed formats this module decodes
TEXEL_BYTES = {
    B8: 1,
    A1R5G5B5: 2,
    A4R4G4B4: 2,
    R5G6B5: 2,
    G8B8: 2,
    X16: 2,
    A8R8G8B8: 4,
    D8R8G8B8: 4,
    Y16_X16: 4,
}

ALIGNMENT = 128


class TextureError(ValueError):
    pass


def base_format(fmt: int) -> int:
    """The format code without the LN and UN flags."""
    return fmt & ~(LN | UN)


def is_linear(fmt: int) -> bool:
    return bool(fmt & LN)


def format_name(fmt: int) -> str:
    name = FORMAT_NAMES.get(base_format(fmt), f"0x{base_format(fmt):02x}")
    flags = [n for bit, n in ((LN, "LN"), (UN, "UN")) if fmt & bit]
    return "|".join([name, *flags])


# -- sizes and layout ----------------------------------------------------------------------


def _align(n: int, a: int = ALIGNMENT) -> int:
    return (n + a - 1) // a * a


def mip_dims(width: int, height: int, levels: int) -> list[tuple[int, int]]:
    return [(max(1, width >> i), max(1, height >> i)) for i in range(levels)]


def level_size(fmt: int, width: int, height: int, pitch: int = 0) -> int:
    f = base_format(fmt)
    if f in BLOCK_BYTES:
        return max(1, (width + 3) // 4) * max(1, (height + 3) // 4) * BLOCK_BYTES[f]
    if f not in TEXEL_BYTES:
        raise TextureError(
            f"unsupported format: expected one of {sorted(FORMAT_NAMES)}, found 0x{fmt:02x}"
        )
    if is_linear(fmt) and pitch:
        return pitch * height
    return width * height * TEXEL_BYTES[f]


def face_size(fmt: int, width: int, height: int, levels: int) -> int:
    """Bytes of one face with its mip chain, padded to 128."""
    return _align(sum(level_size(fmt, w, h) for w, h in mip_dims(width, height, levels)))


def image_size(
    fmt: int, width: int, height: int, levels: int, faces: int = 1, depth: int = 1
) -> int:
    """Total stored bytes, as T5 records it in the GfxImage size field."""
    if depth > 1:
        # Volume: each level holds `depth >> i` slices. Confirmed for one level only
        # (32x32x32 A8R8G8B8 colour LUTs in code_post_gfx_mp); deeper chains are INFERRED.
        n = sum(
            level_size(fmt, w, h) * max(1, depth >> i)
            for i, (w, h) in enumerate(mip_dims(width, height, levels))
        )
        return _align(n)
    return face_size(fmt, width, height, levels) * faces


def level_offsets(
    fmt: int, width: int, height: int, levels: int, faces: int = 1
) -> list[list[int]]:
    """offsets[face][level] of each level within the stored image."""
    fs = face_size(fmt, width, height, levels)
    out = []
    for f in range(faces):
        o, row = f * fs, []
        for w, h in mip_dims(width, height, levels):
            row.append(o)
            o += level_size(fmt, w, h)
        out.append(row)
    return out


# -- swizzle -------------------------------------------------------------------------------


def morton_indices(width: int, height: int) -> np.ndarray:
    """(h, w) array: the swizzled texel index of each (y, x).

    Bits of x and y are interleaved x first, while both have bits left; the larger dimension's
    remaining high bits follow in order. Dimensions must be powers of two.
    """
    if width & (width - 1) or height & (height - 1):
        raise TextureError(f"swizzled texture needs power-of-two size, found {width}x{height}")
    xs = np.arange(width, dtype=np.int64)
    ys = np.arange(height, dtype=np.int64)
    xo = np.zeros(width, dtype=np.int64)
    yo = np.zeros(height, dtype=np.int64)
    bit, sx, sy = 0, 1, 1
    while sx < width or sy < height:
        if sx < width:
            xo |= ((xs // sx) & 1) << bit
            bit += 1
            sx <<= 1
        if sy < height:
            yo |= ((ys // sy) & 1) << bit
            bit += 1
            sy <<= 1
    return yo[:, None] | xo[None, :]


def morton_indices_3d(width: int, height: int, depth: int) -> np.ndarray:
    """(d, h, w) array: swizzled texel index of each (z, y, x); bits interleaved x, y, z."""
    for n in (width, height, depth):
        if n & (n - 1):
            raise TextureError(
                f"swizzled volume needs power-of-two size, found {width}x{height}x{depth}"
            )
    axes = [np.arange(n, dtype=np.int64) for n in (width, height, depth)]
    outs = [np.zeros(n, dtype=np.int64) for n in (width, height, depth)]
    sizes = [width, height, depth]
    steps = [1, 1, 1]
    bit = 0
    while any(st < sz for st, sz in zip(steps, sizes, strict=True)):
        for k in range(3):
            if steps[k] < sizes[k]:
                outs[k] |= ((axes[k] // steps[k]) & 1) << bit
                bit += 1
                steps[k] <<= 1
    return outs[2][:, None, None] | outs[1][None, :, None] | outs[0][None, None, :]


def unswizzle(texels: np.ndarray, width: int, height: int) -> np.ndarray:
    """texels: (w*h, ...) in swizzled order -> (h, w, ...) row-major."""
    return texels[morton_indices(width, height)]


def swizzle(image: np.ndarray) -> np.ndarray:
    """(h, w, ...) row-major -> (w*h, ...) swizzled order."""
    h, w = image.shape[:2]
    out = np.empty((w * h, *image.shape[2:]), dtype=image.dtype)
    out[morton_indices(w, h).ravel()] = image.reshape(w * h, *image.shape[2:])
    return out


# -- DXT -----------------------------------------------------------------------------------


def _rgb565(c: np.ndarray) -> np.ndarray:
    c = c.astype(np.uint32)
    r = (c >> 11) & 31
    g = (c >> 5) & 63
    b = c & 31
    return np.stack([(r << 3) | (r >> 2), (g << 2) | (g >> 4), (b << 3) | (b >> 2)], -1).astype(
        np.int32
    )


def _color_block(blocks: np.ndarray, dxt1: bool) -> np.ndarray:
    """blocks: (n, 8) uint8 -> (n, 16, 4) RGBA; alpha from DXT1 punch-through only."""
    c0 = blocks[:, 0].astype(np.uint16) | (blocks[:, 1].astype(np.uint16) << 8)
    c1 = blocks[:, 2].astype(np.uint16) | (blocks[:, 3].astype(np.uint16) << 8)
    idx = (
        blocks[:, 4].astype(np.uint32)
        | (blocks[:, 5].astype(np.uint32) << 8)
        | (blocks[:, 6].astype(np.uint32) << 16)
        | (blocks[:, 7].astype(np.uint32) << 24)
    )
    p0, p1 = _rgb565(c0), _rgb565(c1)
    four = (c0 > c1) | (not dxt1)
    four = np.asarray(four)[:, None]
    p2 = np.where(four, (2 * p0 + p1) // 3, (p0 + p1) // 2)
    p3 = np.where(four, (p0 + 2 * p1) // 3, 0)
    pal = np.stack([p0, p1, p2, p3], 1)  # (n, 4, 3)
    alpha = np.full((len(blocks), 4), 255, np.int32)
    if dxt1:
        alpha[:, 3] = np.where(four[:, 0], 255, 0)
    pal = np.concatenate([pal, alpha[:, :, None]], -1)
    sel = (idx[:, None] >> (2 * np.arange(16, dtype=np.uint32))) & 3
    return np.take_along_axis(pal, sel[:, :, None].astype(np.int64).repeat(4, 2), 1)


def _alpha_dxt5(blocks: np.ndarray) -> np.ndarray:
    a0 = blocks[:, 0].astype(np.int32)
    a1 = blocks[:, 1].astype(np.int32)
    bits = np.zeros(len(blocks), np.uint64)
    for i in range(6):
        bits |= blocks[:, 2 + i].astype(np.uint64) << np.uint64(8 * i)
    k = np.arange(1, 7)
    eight = (a0 > a1)[:, None]
    pal8 = ((7 - k[None]) * a0[:, None] + k[None] * a1[:, None]) // 7
    k5 = np.arange(1, 5)
    pal6 = ((5 - k5[None]) * a0[:, None] + k5[None] * a1[:, None]) // 5
    pal6 = np.concatenate(
        [pal6, np.zeros((len(blocks), 1), np.int32), np.full((len(blocks), 1), 255)], 1
    )
    pal = np.concatenate([a0[:, None], a1[:, None], np.where(eight, pal8, pal6)], 1)
    sel = (bits[:, None] >> (np.uint64(3) * np.arange(16, dtype=np.uint64))) & np.uint64(7)
    return np.take_along_axis(pal, sel.astype(np.int64), 1)


def _alpha_dxt3(blocks: np.ndarray) -> np.ndarray:
    lo = blocks[:, :8]
    nib = np.stack([lo & 15, lo >> 4], -1).reshape(len(blocks), 16).astype(np.int32)
    return nib * 17


def decode_dxt(data: bytes, fmt: int, width: int, height: int) -> np.ndarray:
    f = base_format(fmt)
    bw, bh = max(1, (width + 3) // 4), max(1, (height + 3) // 4)
    n = bw * bh
    need = n * BLOCK_BYTES[f]
    if len(data) < need:
        raise TextureError(
            f"{format_name(fmt)} {width}x{height}: expected {need} bytes, found {len(data)}"
        )
    raw = np.frombuffer(data, np.uint8, need).reshape(n, BLOCK_BYTES[f])
    if f == DXT1:
        px = _color_block(raw, True)
    else:
        px = _color_block(raw[:, 8:], False)
        px[:, :, 3] = _alpha_dxt5(raw[:, :8]) if f == DXT45 else _alpha_dxt3(raw[:, :8])
    img = px.reshape(bh, bw, 4, 4, 4).transpose(0, 2, 1, 3, 4).reshape(bh * 4, bw * 4, 4)
    return img[:height, :width].astype(np.uint8)


def _blocks_of(rgba: np.ndarray) -> tuple[np.ndarray, int, int]:
    h, w = rgba.shape[:2]
    bh, bw = (h + 3) // 4, (w + 3) // 4
    pad = np.pad(rgba, ((0, bh * 4 - h), (0, bw * 4 - w), (0, 0)), mode="edge")
    blk = pad.reshape(bh, 4, bw, 4, 4).transpose(0, 2, 1, 3, 4).reshape(bh * bw, 16, 4)
    return blk.astype(np.float32), bw, bh


def _to565(c: np.ndarray) -> np.ndarray:
    c = np.clip(np.rint(c), 0, 255).astype(np.uint32)
    return ((c[..., 0] >> 3) << 11) | ((c[..., 1] >> 2) << 5) | (c[..., 2] >> 3)


def _encode_color(blk: np.ndarray, dxt1_alpha: bool) -> np.ndarray:
    """blk: (n, 16, 4) float -> (n, 8) uint8 colour blocks (range fit on the principal axis)."""
    rgb = blk[:, :, :3]
    mean = rgb.mean(1, keepdims=True)
    cen = rgb - mean
    cov = np.einsum("nki,nkj->nij", cen, cen)
    axis = np.ones((len(blk), 3), np.float32)
    for _ in range(8):  # power iteration
        axis = np.einsum("nij,nj->ni", cov, axis)
        norm = np.linalg.norm(axis, axis=1, keepdims=True)
        axis = np.where(norm > 1e-6, axis / np.maximum(norm, 1e-6), 1 / np.sqrt(3))
    t = np.einsum("nki,ni->nk", cen, axis)
    hi = mean[:, 0] + axis * t.max(1, keepdims=True)
    lo = mean[:, 0] + axis * t.min(1, keepdims=True)
    c0, c1 = _to565(hi), _to565(lo)
    swap = c0 < c1
    c0, c1 = np.where(swap, c1, c0), np.where(swap, c0, c1)
    transparent = (blk[:, :, 3] < 128) if dxt1_alpha else np.zeros(blk.shape[:2], bool)
    three = transparent.any(1)
    # three-colour mode needs c0 <= c1
    c0, c1 = np.where(three, np.minimum(c0, c1), c0), np.where(three, np.maximum(c0, c1), c1)
    equal = (c0 == c1) & ~three
    p0, p1 = _rgb565(c0).astype(np.float32), _rgb565(c1).astype(np.float32)
    pal4 = np.stack([p0, p1, (2 * p0 + p1) / 3, (p0 + 2 * p1) / 3], 1)
    pal3 = np.stack([p0, p1, (p0 + p1) / 2, np.full_like(p0, 1e9)], 1)
    pal = np.where(three[:, None, None], pal3, pal4)
    d = ((rgb[:, :, None, :] - pal[:, None, :, :]) ** 2).sum(-1)
    sel = d.argmin(2).astype(np.uint32)
    sel = np.where(transparent, 3, sel)
    sel = np.where(equal[:, None], 0, sel)
    idx = (sel << (2 * np.arange(16, dtype=np.uint32))).sum(1).astype(np.uint32)
    out = np.empty((len(blk), 8), np.uint8)
    out[:, 0], out[:, 1] = c0 & 255, c0 >> 8
    out[:, 2], out[:, 3] = c1 & 255, c1 >> 8
    for i in range(4):
        out[:, 4 + i] = (idx >> (8 * i)) & 255
    return out


def _encode_alpha5(a: np.ndarray) -> np.ndarray:
    a0 = a.max(1).astype(np.int32)
    a1 = a.min(1).astype(np.int32)
    k = np.arange(1, 7)
    pal = np.concatenate(
        [a0[:, None], a1[:, None], ((7 - k[None]) * a0[:, None] + k[None] * a1[:, None]) // 7], 1
    )
    sel = np.abs(a[:, :, None] - pal[:, None, :]).argmin(2).astype(np.uint64)
    sel = np.where((a0 == a1)[:, None], np.uint64(0), sel)
    bits = (sel << (np.uint64(3) * np.arange(16, dtype=np.uint64))).sum(1).astype(np.uint64)
    out = np.empty((len(a), 8), np.uint8)
    out[:, 0], out[:, 1] = a0, a1
    for i in range(6):
        out[:, 2 + i] = ((bits >> np.uint64(8 * i)) & np.uint64(255)).astype(np.uint8)
    return out


def encode_dxt(rgba: np.ndarray, fmt: int) -> bytes:
    f = base_format(fmt)
    blk, _, _ = _blocks_of(rgba)
    if f == DXT1:
        return _encode_color(blk, True).tobytes()
    color = _encode_color(blk, False)
    if f == DXT45:
        alpha = _encode_alpha5(blk[:, :, 3])
    else:
        q = np.clip(np.rint(blk[:, :, 3] / 17), 0, 15).astype(np.uint8)
        alpha = (q[:, 0::2] | (q[:, 1::2] << 4)).astype(np.uint8)
    return np.concatenate([alpha, color], 1).tobytes()


# -- uncompressed --------------------------------------------------------------------------


def _expand(v: np.ndarray, bits: int) -> np.ndarray:
    v = v.astype(np.uint32)
    return ((v * 255 + ((1 << bits) - 1) // 2) // ((1 << bits) - 1)).astype(np.uint8)


def decode_plain(data: bytes, fmt: int, width: int, height: int, pitch: int = 0) -> np.ndarray:
    """Uncompressed level -> RGBA, before remap. B8 lands in every colour channel."""
    f = base_format(fmt)
    bpp = TEXEL_BYTES[f]
    if is_linear(fmt):
        pitch = pitch or width * bpp
        need = pitch * (height - 1) + width * bpp
        if len(data) < need:
            raise TextureError(
                f"{format_name(fmt)} {width}x{height}: expected {need} bytes, found {len(data)}"
            )
        rows = np.frombuffer(data, np.uint8, need + (pitch - width * bpp)).reshape(height, pitch)
        tex = rows[:, : width * bpp].reshape(height * width, bpp)
        tex = tex.reshape(height, width, bpp)
    else:
        need = width * height * bpp
        if len(data) < need:
            raise TextureError(
                f"{format_name(fmt)} {width}x{height}: expected {need} bytes, found {len(data)}"
            )
        tex = unswizzle(np.frombuffer(data, np.uint8, need).reshape(-1, bpp), width, height)
    out = np.empty((height, width, 4), np.uint8)
    if f in (A8R8G8B8, D8R8G8B8):
        out[..., 3], out[..., 0], out[..., 1], out[..., 2] = (tex[..., i] for i in range(4))
        if f == D8R8G8B8:
            out[..., 3] = 255
    elif f == B8:
        out[..., :3] = tex[..., :1]
        out[..., 3] = 255
    elif f == G8B8:
        out[..., 0] = 0
        out[..., 1], out[..., 2] = tex[..., 0], tex[..., 1]
        out[..., 3] = 255
    elif f in (A1R5G5B5, A4R4G4B4, R5G6B5, X16):
        v = (tex[..., 0].astype(np.uint16) << 8) | tex[..., 1]
        if f == R5G6B5:
            out[..., :3] = _rgb565(v).astype(np.uint8)
            out[..., 3] = 255
        elif f == A1R5G5B5:
            out[..., 0], out[..., 1], out[..., 2] = (_expand((v >> s) & 31, 5) for s in (10, 5, 0))
            out[..., 3] = np.where(v >> 15, 255, 0)
        elif f == A4R4G4B4:
            out[..., 3], out[..., 0], out[..., 1], out[..., 2] = (
                _expand((v >> s) & 15, 4) for s in (12, 8, 4, 0)
            )
        else:  # X16: top byte into grey
            out[..., :3] = (v >> 8)[..., None]
            out[..., 3] = 255
    elif f == Y16_X16:
        out[..., 0], out[..., 1] = tex[..., 0], tex[..., 2]
        out[..., 2], out[..., 3] = 0, 255
    else:
        raise TextureError(f"unsupported format 0x{fmt:02x}")
    return out


def encode_plain(rgba: np.ndarray, fmt: int) -> bytes:
    f = base_format(fmt)
    h, w = rgba.shape[:2]
    if f in (A8R8G8B8, D8R8G8B8):
        tex = rgba[..., [3, 0, 1, 2]].copy()
        if f == D8R8G8B8:
            tex[..., 0] = 255
    elif f == B8:
        tex = rgba[..., :1].copy()
    elif f == G8B8:
        tex = rgba[..., 1:3].copy()
    else:
        raise TextureError(f"encoding 0x{fmt:02x} is not supported")
    tex = tex.astype(np.uint8)
    if is_linear(fmt):
        return tex.tobytes()
    return swizzle(tex).tobytes()


# -- remap ---------------------------------------------------------------------------------


def apply_remap(rgba: np.ndarray, remap: int) -> np.ndarray:
    """Apply a CellGcmTexture.remap word to decoded A,R,G,B channels.

    remap bits: [15:14] outB [13:12] outG [11:10] outR [9:8] outA (0 zero, 1 one, 2 remap),
    [7:6] inB [5:4] inG [3:2] inR [1:0] inA (0 A, 1 R, 2 G, 3 B). 0xaae4 is identity.
    """
    src = {0: rgba[..., 3], 1: rgba[..., 0], 2: rgba[..., 1], 3: rgba[..., 2]}
    out = np.empty_like(rgba)
    for ch, (osh, ish) in {3: (8, 0), 0: (10, 2), 1: (12, 4), 2: (14, 6)}.items():
        op = (remap >> osh) & 3
        if op == 0:
            out[..., ch] = 0
        elif op == 1:
            out[..., ch] = 255
        else:
            out[..., ch] = src[(remap >> ish) & 3]
    return out


# -- whole images --------------------------------------------------------------------------


def decode_level(data: bytes, fmt: int, width: int, height: int, pitch: int = 0) -> np.ndarray:
    if base_format(fmt) in BLOCK_BYTES:
        return decode_dxt(data, fmt, width, height)
    return decode_plain(data, fmt, width, height, pitch)


def decode(
    data: bytes,
    fmt: int,
    width: int,
    height: int,
    levels: int = 1,
    *,
    level: int = 0,
    face: int = 0,
    faces: int = 1,
    remap: int | None = None,
    pitch: int = 0,
) -> np.ndarray:
    """Stored image bytes -> RGBA uint8 (h, w, 4) of one level of one face."""
    off = level_offsets(fmt, width, height, levels, faces)[face][level]
    w, h = mip_dims(width, height, levels)[level]
    img = decode_level(data[off:], fmt, w, h, pitch if level == 0 else 0)
    if remap is not None:
        img = apply_remap(img, remap)
    return img


def decode_volume(data: bytes, fmt: int, width: int, height: int, depth: int) -> np.ndarray:
    """Level 0 of a swizzled uncompressed volume texture -> RGBA (d, h, w, 4)."""
    f = base_format(fmt)
    if f not in TEXEL_BYTES or is_linear(fmt):
        raise TextureError(
            f"volume decode supports swizzled uncompressed formats, found {format_name(fmt)}"
        )
    bpp = TEXEL_BYTES[f]
    need = width * height * depth * bpp
    if len(data) < need:
        raise TextureError(
            f"volume {width}x{height}x{depth}: expected {need} bytes, found {len(data)}"
        )
    tex = np.frombuffer(data, np.uint8, need).reshape(-1, bpp)[
        morton_indices_3d(width, height, depth)
    ]
    # Re-swizzle each slice as 2D so decode_plain can do the channel work.
    out = np.empty((depth, height, width, 4), np.uint8)
    for z in range(depth):
        out[z] = decode_plain(swizzle(tex[z]).tobytes(), fmt, width, height)
    return out


def encode_volume(rgba: np.ndarray, fmt: int) -> bytes:
    """RGBA (d, h, w, 4) -> one swizzled volume level."""
    d, h, w = rgba.shape[:3]
    slices = [
        unswizzle(np.frombuffer(encode_plain(rgba[z], fmt), np.uint8).reshape(w * h, -1), w, h)
        for z in range(d)
    ]
    vol = np.stack(slices)
    out = np.empty((w * h * d, vol.shape[-1]), np.uint8)
    out[morton_indices_3d(w, h, d).ravel()] = vol.reshape(w * h * d, -1)
    raw = out.tobytes()
    return raw + bytes(_align(len(raw)) - len(raw))


def mip_chain(rgba: np.ndarray, levels: int) -> list[np.ndarray]:
    """Box-filtered mips, level 0 first."""
    out = [rgba]
    for _ in range(levels - 1):
        a = out[-1].astype(np.float32)
        h, w = a.shape[:2]
        if h > 1:
            a = (a[0::2] + a[1::2]) / 2 if h % 2 == 0 else a
        if w > 1:
            a = (a[:, 0::2] + a[:, 1::2]) / 2 if w % 2 == 0 else a
        out.append(np.clip(np.rint(a), 0, 255).astype(np.uint8))
    return out


def full_levels(width: int, height: int) -> int:
    return max(width, height).bit_length()


def encode_level(rgba: np.ndarray, fmt: int) -> bytes:
    if base_format(fmt) in BLOCK_BYTES:
        return encode_dxt(rgba, fmt)
    return encode_plain(rgba, fmt)


def assemble(fmt: int, faces_levels: list[list[bytes]]) -> bytes:
    """Per-face, per-level bytes -> stored image (faces padded to 128)."""
    out = bytearray()
    for levels in faces_levels:
        face = b"".join(levels)
        out += face + bytes(_align(len(face)) - len(face))
    return bytes(out)


def encode(rgba: np.ndarray | list[np.ndarray], fmt: int, levels: int | None = None) -> bytes:
    """RGBA (h, w, 4), or a list of six faces, -> stored bytes with a generated mip chain."""
    faces = rgba if isinstance(rgba, list) else [rgba]
    h, w = faces[0].shape[:2]
    n = levels or full_levels(w, h)
    return assemble(fmt, [[encode_level(m, fmt) for m in mip_chain(f, n)] for f in faces])


def split(
    data: bytes, fmt: int, width: int, height: int, levels: int, faces: int = 1
) -> list[list[bytes]]:
    """Stored image -> per-face, per-level bytes."""
    offs = level_offsets(fmt, width, height, levels, faces)
    dims = mip_dims(width, height, levels)
    return [[data[o : o + level_size(fmt, *dims[i])] for i, o in enumerate(row)] for row in offs]


# -- CellGcmTexture and .pak ----------------------------------------------------------------


@dataclass
class GcmTexture:
    """The 24-byte CellGcmTexture at the start of a T5 PS3 GfxImage (big-endian)."""

    format: int
    mipmap: int
    dimension: int
    cubemap: int
    remap: int
    width: int
    height: int
    depth: int
    location: int
    pitch: int
    offset: int

    SIZE = 24

    @classmethod
    def parse(cls, data: bytes, at: int = 0) -> GcmTexture:
        f, m, dim, cube, remap, w, h, d, loc, _pad, pitch, off = struct.unpack_from(
            ">BBBBIHHHBBII", data, at
        )
        return cls(f, m, dim, cube, remap, w, h, d, loc, pitch, off)

    def pack(self) -> bytes:
        return struct.pack(
            ">BBBBIHHHBBII",
            self.format,
            self.mipmap,
            self.dimension,
            self.cubemap,
            self.remap,
            self.width,
            self.height,
            self.depth,
            self.location,
            0,
            self.pitch,
            self.offset,
        )

    @property
    def faces(self) -> int:
        return 6 if self.cubemap else 1

    def stored_size(self) -> int:
        return image_size(
            self.format,
            self.width,
            self.height,
            self.mipmap,
            self.faces,
            self.depth if self.dimension == 3 else 1,
        )


PAK_MAGIC = b"pak2"
PAK_SECTOR = 0x800


class Pak:
    """A T5 PS3 .pak image/sound pack: 'pak2' header, a u32 start-sector table, sector data.

        0x00 'pak2'   0x04 u32 build time (unix)   0x08 u32 unknown
        0x0c u32 entry count   0x10 u32 0x800 (sector size)   0x14 u32 header bytes
        0x18 u32 0    0x1c u32[count] start sector of each entry

    Entries are not stored with sizes; the GfxImage part record gives the byte size, and a
    table that is not ascending (img_patch.pak) still holds valid starts.
    """

    def __init__(self, path):
        self.path = path
        with open(path, "rb") as f:
            head = f.read(0x1C)
            if head[:4] != PAK_MAGIC:
                raise TextureError(f"pak magic: expected {PAK_MAGIC!r}, found {head[:4]!r} at 0x0")
            _, self.timestamp, self.unknown, self.count, self.sector, self.header_size, _ = (
                struct.unpack(">4sIIIIII", head)
            )
            self.starts = struct.unpack(f">{self.count}I", f.read(4 * self.count))

    def offset(self, index: int) -> int:
        return self.starts[index] * self.sector

    def read(self, index: int, size: int) -> bytes:
        with open(self.path, "rb") as f:
            f.seek(self.offset(index))
            data = f.read(size)
        if len(data) != size:
            raise TextureError(
                f"pak entry {index}: expected {size} bytes at 0x{self.offset(index):x}, "
                f"found {len(data)}"
            )
        return data


# -- DDS -----------------------------------------------------------------------------------

_DDSD = 0x1 | 0x2 | 0x4 | 0x1000  # caps height width pixelformat
_DDSD_MIPMAPCOUNT = 0x20000
_DDSD_LINEARSIZE = 0x80000
_DDSD_PITCH = 0x8
_DDPF_FOURCC = 0x4
_DDPF_RGB = 0x40
_DDPF_ALPHAPIXELS = 0x1
_DDPF_LUMINANCE = 0x20000
_DDSCAPS_TEXTURE = 0x1000
_DDSCAPS_COMPLEX = 0x8
_DDSCAPS_MIPMAP = 0x400000
_DDSCAPS2_CUBEMAP_ALL = 0x200 | 0xFC00
_FOURCC = {DXT1: b"DXT1", DXT23: b"DXT3", DXT45: b"DXT5"}


@dataclass
class Dds:
    fmt: int
    width: int
    height: int
    levels: int
    faces: list[list[bytes]] = field(default_factory=list)  # [face][level] in GCM byte order

    def to_stored(self) -> bytes:
        return assemble(self.fmt, self.faces)


def _dds_level_to_gcm(raw: bytes, fmt: int, w: int, h: int) -> bytes:
    f = base_format(fmt)
    if f in BLOCK_BYTES:
        return raw
    a = np.frombuffer(raw, np.uint8)
    if f == B8:
        img = np.repeat(a.reshape(h, w, 1), 4, 2)
    else:  # DDS A8R8G8B8 is little-endian: bytes B, G, R, A
        bgra = a.reshape(h, w, 4)
        img = bgra[..., [2, 1, 0, 3]]
    return encode_plain(img, fmt)


def _gcm_level_to_dds(raw: bytes, fmt: int, w: int, h: int) -> bytes:
    f = base_format(fmt)
    if f in BLOCK_BYTES:
        return raw
    img = decode_plain(raw, fmt, w, h)
    if f == B8:
        return img[..., 0].tobytes()
    return img[..., [2, 1, 0, 3]].tobytes()


def read_dds(data: bytes, fmt: int | None = None) -> Dds:
    """DXT1/3/5, A8R8G8B8, X8R8G8B8 and L8 DDS files, with mips and cube faces."""
    if data[:4] != b"DDS ":
        raise TextureError(f"DDS magic: expected b'DDS ', found {data[:4]!r} at 0x0")
    (size, flags, h, w, pitch, depth, mips) = struct.unpack_from("<7I", data, 4)
    pf_flags, fourcc, bits, rm, gm, bm, am = struct.unpack_from("<I4s5I", data, 0x50)
    caps2 = struct.unpack_from("<I", data, 0x70)[0]
    levels = mips if flags & _DDSD_MIPMAPCOUNT and mips else 1
    nfaces = 6 if caps2 & 0x200 else 1
    if pf_flags & _DDPF_FOURCC:
        rev = {v: k for k, v in _FOURCC.items()}
        if fourcc not in rev:
            raise TextureError(f"DDS fourCC: expected DXT1/DXT3/DXT5, found {fourcc!r} at 0x54")
        gfmt = rev[fourcc]
    elif pf_flags & _DDPF_LUMINANCE and bits == 8:
        gfmt = B8
    elif pf_flags & _DDPF_RGB and bits == 32 and rm == 0xFF0000:
        gfmt = A8R8G8B8 if pf_flags & _DDPF_ALPHAPIXELS else D8R8G8B8
    else:
        raise TextureError(
            f"DDS pixel format: unsupported flags 0x{pf_flags:x} bits {bits} at 0x50"
        )
    if fmt is not None:
        gfmt = fmt
    off = 128
    dims = mip_dims(w, h, levels)
    faces = []
    for _ in range(nfaces):
        row = []
        for lw, lh in dims:
            if base_format(gfmt) in BLOCK_BYTES:
                n = level_size(gfmt, lw, lh)
            else:
                n = lw * lh * (1 if base_format(gfmt) == B8 else 4)
            if off + n > len(data):
                raise TextureError(
                    f"DDS level: expected {n} bytes at 0x{off:x}, found {len(data) - off}"
                )
            row.append(_dds_level_to_gcm(data[off : off + n], gfmt, lw, lh))
            off += n
        faces.append(row)
    return Dds(gfmt, w, h, levels, faces)


def write_dds(dds: Dds) -> bytes:
    f = base_format(dds.fmt)
    cube = len(dds.faces) == 6
    flags = _DDSD | (_DDSD_MIPMAPCOUNT if dds.levels > 1 else 0)
    caps = _DDSCAPS_TEXTURE | (_DDSCAPS_MIPMAP | _DDSCAPS_COMPLEX if dds.levels > 1 else 0)
    if cube:
        caps |= _DDSCAPS_COMPLEX
    if f in BLOCK_BYTES:
        flags |= _DDSD_LINEARSIZE
        pitch = level_size(f, dds.width, dds.height)
        pf = struct.pack("<II4s5I", 32, _DDPF_FOURCC, _FOURCC[f], 0, 0, 0, 0, 0)
    elif f == B8:
        flags |= _DDSD_PITCH
        pitch = dds.width
        pf = struct.pack("<II4s5I", 32, _DDPF_LUMINANCE, b"\0" * 4, 8, 0xFF, 0, 0, 0)
    else:
        flags |= _DDSD_PITCH
        pitch = dds.width * 4
        pf = struct.pack(
            "<II4s5I",
            32,
            _DDPF_RGB | _DDPF_ALPHAPIXELS,
            b"\0" * 4,
            32,
            0xFF0000,
            0xFF00,
            0xFF,
            0xFF000000,
        )
    hdr = struct.pack("<4s7I", b"DDS ", 124, flags, dds.height, dds.width, pitch, 0, dds.levels)
    hdr += bytes(44) + pf
    hdr += struct.pack("<4I", caps, _DDSCAPS2_CUBEMAP_ALL if cube else 0, 0, 0) + bytes(4)
    body = bytearray()
    dims = mip_dims(dds.width, dds.height, dds.levels)
    for row in dds.faces:
        for (lw, lh), raw in zip(dims, row, strict=True):
            body += _gcm_level_to_dds(raw, dds.fmt, lw, lh)
    return hdr + bytes(body)


def stored_to_dds(
    data: bytes, fmt: int, width: int, height: int, levels: int, faces: int = 1
) -> bytes:
    return write_dds(
        Dds(fmt, width, height, levels, split(data, fmt, width, height, levels, faces))
    )


# -- PNG -----------------------------------------------------------------------------------


def write_png(rgba: np.ndarray) -> bytes:
    h, w = rgba.shape[:2]
    raw = np.concatenate([np.zeros((h, 1), np.uint8), rgba.astype(np.uint8).reshape(h, w * 4)], 1)

    def chunk(kind: bytes, body: bytes) -> bytes:
        return (
            struct.pack(">I", len(body)) + kind + body + struct.pack(">I", zlib.crc32(kind + body))
        )

    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw.tobytes(), 6))
        + chunk(b"IEND", b"")
    )


def read_png(data: bytes) -> np.ndarray:
    """8-bit, non-interlaced grey / grey+alpha / RGB / RGBA PNG -> RGBA uint8."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise TextureError(f"PNG magic: expected 89 50 4e 47, found {data[:4].hex()} at 0x0")
    o, idat, hdr = 8, bytearray(), None
    while o < len(data):
        n, kind = struct.unpack_from(">I4s", data, o)
        body = data[o + 8 : o + 8 + n]
        if kind == b"IHDR":
            hdr = struct.unpack(">IIBBBBB", body)
        elif kind == b"IDAT":
            idat += body
        o += 12 + n
    if hdr is None:
        raise TextureError("PNG: no IHDR chunk")
    w, h, depth, ctype, _, _, interlace = hdr
    chans = {0: 1, 2: 3, 4: 2, 6: 4}.get(ctype)
    if depth != 8 or chans is None or interlace:
        raise TextureError(
            f"PNG: expected 8-bit non-interlaced grey/RGB(A), found depth {depth} type {ctype}"
        )
    raw = np.frombuffer(zlib.decompress(bytes(idat)), np.uint8).reshape(h, 1 + w * chans)
    out = np.zeros((h, w * chans), np.uint8)
    prev = np.zeros(w * chans, np.int32)
    for y in range(h):
        ft, line = raw[y, 0], raw[y, 1:].astype(np.int32)
        if ft == 0:
            cur = line
        elif ft == 2:
            cur = (line + prev) & 255
        elif ft in (1, 3, 4):
            cur = np.zeros_like(line)
            for x in range(len(line)):
                a = cur[x - chans] if x >= chans else 0
                b = prev[x]
                if ft == 1:
                    p = a
                elif ft == 3:
                    p = (a + b) // 2
                else:
                    c = prev[x - chans] if x >= chans else 0
                    pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                    p = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                cur[x] = (line[x] + p) & 255
        else:
            raise TextureError(f"PNG: unknown filter {ft} on row {y}")
        out[y] = cur
        prev = cur
    px = out.reshape(h, w, chans)
    if chans == 4:
        return px
    rgba = np.full((h, w, 4), 255, np.uint8)
    if chans in (1, 2):
        rgba[..., :3] = px[..., :1]
        if chans == 2:
            rgba[..., 3] = px[..., 1]
    else:
        rgba[..., :3] = px
    return rgba
